# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dajiejie/dida-sgx-sealing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dajiejie/dida-sgx-sealing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dajiejie/dida-sgx-sealing/CMakeFiles /home/dajiejie/dida-sgx-sealing/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dajiejie/dida-sgx-sealing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named trusted_lib-edlobj

# Build rule for target.
trusted_lib-edlobj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trusted_lib-edlobj
.PHONY : trusted_lib-edlobj

# fast build rule for target.
trusted_lib-edlobj/fast:
	$(MAKE) -f sample/DIDA/CMakeFiles/trusted_lib-edlobj.dir/build.make sample/DIDA/CMakeFiles/trusted_lib-edlobj.dir/build
.PHONY : trusted_lib-edlobj/fast

#=============================================================================
# Target rules for targets named enclave-edlobj

# Build rule for target.
enclave-edlobj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enclave-edlobj
.PHONY : enclave-edlobj

# fast build rule for target.
enclave-edlobj/fast:
	$(MAKE) -f sample/DIDA/CMakeFiles/enclave-edlobj.dir/build.make sample/DIDA/CMakeFiles/enclave-edlobj.dir/build
.PHONY : enclave-edlobj/fast

#=============================================================================
# Target rules for targets named enclave

# Build rule for target.
enclave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enclave
.PHONY : enclave

# fast build rule for target.
enclave/fast:
	$(MAKE) -f sample/DIDA/CMakeFiles/enclave.dir/build.make sample/DIDA/CMakeFiles/enclave.dir/build
.PHONY : enclave/fast

#=============================================================================
# Target rules for targets named trusted_lib

# Build rule for target.
trusted_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trusted_lib
.PHONY : trusted_lib

# fast build rule for target.
trusted_lib/fast:
	$(MAKE) -f sample/DIDA/CMakeFiles/trusted_lib.dir/build.make sample/DIDA/CMakeFiles/trusted_lib.dir/build
.PHONY : trusted_lib/fast

#=============================================================================
# Target rules for targets named didasgx

# Build rule for target.
didasgx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 didasgx
.PHONY : didasgx

# fast build rule for target.
didasgx/fast:
	$(MAKE) -f sample/DIDA/CMakeFiles/didasgx.dir/build.make sample/DIDA/CMakeFiles/didasgx.dir/build
.PHONY : didasgx/fast

#=============================================================================
# Target rules for targets named enclave-sign

# Build rule for target.
enclave-sign: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enclave-sign
.PHONY : enclave-sign

# fast build rule for target.
enclave-sign/fast:
	$(MAKE) -f sample/DIDA/CMakeFiles/enclave-sign.dir/build.make sample/DIDA/CMakeFiles/enclave-sign.dir/build
.PHONY : enclave-sign/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... trusted_lib-edlobj"
	@echo "... enclave-edlobj"
	@echo "... enclave"
	@echo "... trusted_lib"
	@echo "... didasgx"
	@echo "... enclave-sign"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

